### ISSUE TITLE
PDF voucher generation works only for languages using ISO-8859-1 

### ISSUE THREAD

**Issue by allefm** [mcmilk/UniFi-HotSpot-Manager#1]
Wonderful project!

But PDF voucher generation works only for languages using ISO-8859-1 characters. 
No Greek, no Cyrilic. Even no Latin using Baltic languages or Serb-Horvatic. 

Would it be hard to migrate to tFPDF or any other library supporting UTF fonts?

**Comment by mcmilk** [comment]
Hello, it's not hard to migrate to tFPDF ... I have done this allready... it's somewhere in my local repositories. I hope, that I have some time to take a look at them...

I also wanted to change the whole process a bit, so that the qr-code on the voucher will be `the` activation url ... and the wifi settings are on an seperate page which can be printed as generic information about network settings and so on...

The local thing supported all languages exept CJK characters...

**Comment by mcmilk** [comment]
I some months I need to touch the code... I will upload it then.
